version: "3"

services:

  bot:
    labels:
      shipyard.route: '/'
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV:-development}
    environment:
      AIRTABLE_API_KEY: ${AIRTABLE_API_KEY}
      AIRTABLE_BASE_ID: ${AIRTABLE_BASE_ID}
      AIRTABLE_REQUESTS_VIEW_NAME: ${AIRTABLE_REQUESTS_VIEW_NAME}
      AIRTABLE_REQUESTS_VIEW_URL: ${AIRTABLE_REQUESTS_VIEW_URL}
      AIRTABLE_VOLUNTEERS_VIEW_NAME: ${AIRTABLE_VOLUNTEERS_VIEW_NAME}
      AIRTABLE_VOLUNTEERS_VIEW_URL: ${AIRTABLE_VOLUNTEERS_VIEW_URL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      MAPQUEST_KEY: ${MAPQUEST_KEY}
      NODE_ENV: ${NODE_ENV:-development}
      SLACK_ALERT_CHANNEL_ID: ${SLACK_ALERT_CHANNEL_ID}
      SLACK_CHANNEL_ID: ${SLACK_CHANNEL_ID}
      SLACK_XOXB: ${SLACK_XOXB}
      VOLUNTEER_DISPATCH_PREVENT_PROCESSING: ${VOLUNTEER_DISPATCH_PREVENT_PROCESSING}
      VOLUNTEER_DISPATCH_STATE: ${VOLUNTEER_DISPATCH_STATE}
    volumes:
      - "./src:/srv/src"
    ports:
      - '3000:3000'
